spring:
  datasource:
#    DENTRO DE CONTENEDOR DOCKER
#    url: jdbc:postgresql://db:5432/springboot_db
#    FUERA DE CONTENEDOR DOCKER
    url: ${POSTGRES_URL}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
