spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/springboot_db
    username: springboot_user
    password: springboot_password
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
